{{- if .Values.service.dns.tcp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "powerdns.fullname" . }}-service-dns-tcp
  labels:
{{ include "powerdns.labels" . | indent 4 }}
{{- with .Values.service.dns.tcp.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.dns.tcp.type }}
  {{- if .Values.service.dns.tcp.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.dns.tcp.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.dns.tcp.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.dns.tcp.externalIPs | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.dns.tcp.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    app.kubernetes.io/name: {{ include "powerdns.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    powerdns.com/role: api
{{- end }}

